// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0z7m8GNx1EpjC-ZAh3fqX4ltlFo6w67o',
    appId: '1:763346326168:web:79795dae90c1338007f6ed',
    messagingSenderId: '763346326168',
    projectId: 'trackai-3648c',
    authDomain: 'trackai-3648c.firebaseapp.com',
    storageBucket: 'trackai-3648c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jTDQOlYlZpXA6UMgM3rGcYFi11kLCXs',
    appId: '1:763346326168:android:12d9989c46bf831007f6ed',
    messagingSenderId: '763346326168',
    projectId: 'trackai-3648c',
    storageBucket: 'trackai-3648c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiBI56GbkffEBzoAnkCmizZ0qzSdgshjU',
    appId: '1:763346326168:ios:9408634b48d5380207f6ed',
    messagingSenderId: '763346326168',
    projectId: 'trackai-3648c',
    storageBucket: 'trackai-3648c.firebasestorage.app',
    androidClientId: '763346326168-0851bnimjpqkb344snljkm4dhu1ko637.apps.googleusercontent.com',
    iosClientId: '763346326168-jq8lkrsuqlapcint6np2h6boucee22ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiBI56GbkffEBzoAnkCmizZ0qzSdgshjU',
    appId: '1:763346326168:ios:9408634b48d5380207f6ed',
    messagingSenderId: '763346326168',
    projectId: 'trackai-3648c',
    storageBucket: 'trackai-3648c.firebasestorage.app',
    androidClientId: '763346326168-0851bnimjpqkb344snljkm4dhu1ko637.apps.googleusercontent.com',
    iosClientId: '763346326168-jq8lkrsuqlapcint6np2h6boucee22ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0z7m8GNx1EpjC-ZAh3fqX4ltlFo6w67o',
    appId: '1:763346326168:web:07cae36217a9b58d07f6ed',
    messagingSenderId: '763346326168',
    projectId: 'trackai-3648c',
    authDomain: 'trackai-3648c.firebaseapp.com',
    storageBucket: 'trackai-3648c.firebasestorage.app',
  );

}