// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDN2LXqZRGtCCA9NEQb31-KEWPkDpJq04',
    appId: '1:552598421713:web:cdba4f1f413c4bfc3605f0',
    messagingSenderId: '552598421713',
    projectId: 'trackai-d6976',
    authDomain: 'trackai-d6976.firebaseapp.com',
    storageBucket: 'trackai-d6976.firebasestorage.app',
    measurementId: 'G-H6PY79VE0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NGhwfzA0ur3n87V8gXFZ8o5Z-lQfF04',
    appId: '1:552598421713:android:aca0ea8fb0c64e163605f0',
    messagingSenderId: '552598421713',
    projectId: 'trackai-d6976',
    storageBucket: 'trackai-d6976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NGhwfzA0ur3n87V8gXFZ8o5Z-lQfF04',
    appId: '1:552598421713:ios:a108f80421ed344f3605f0',
    messagingSenderId: '552598421713',
    projectId: 'trackai-d6976',
    storageBucket: 'trackai-d6976.firebasestorage.app',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5NGhwfzA0ur3n87V8gXFZ8o5Z-lQfF04',
    appId: '1:552598421713:ios:a108f80421ed344f3605f0',
    messagingSenderId: '552598421713',
    projectId: 'trackai-d6976',
    storageBucket: 'trackai-d6976.firebasestorage.app',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDN2LXqZRGtCCA9NEQb31-KEWPkDpJq04',
    appId: '1:552598421713:web:cdba4f1f413c4bfc3605f0',
    messagingSenderId: '552598421713',
    projectId: 'trackai-d6976',
    authDomain: 'trackai-d6976.firebaseapp.com',
    storageBucket: 'trackai-d6976.firebasestorage.app',
  );
}
